config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as rooms_views

app_name = "core"

urlpatterns = [path("", rooms_views.HomeView.as_view(), name="home")]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path("switch/<int:pk>", views.switch_likes, name="favRoom"),
    path("favs/", views.SeeFavsView.as_view(), name="favs"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>?/", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
]

rooms/models.py
from django.db import models
from django_countries.fields import CountryField
from django.urls import reverse
from core import models as core_models
from cal import Calendar
import datetime
from dateutil import relativedelta


class AbstractItem(core_models.TimeStampedModel):
    """Abastract Item"""

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class RoomType(AbstractItem):
    """RoomType Model Definition"""

    class Meta:
        verbose_name = "Room Type"
        ordering = ["name"]


class Amenity(AbstractItem):
    """Amenity Model Definition"""

    class Meta:
        verbose_name_plural = "Amenities"


class Facility(AbstractItem):
    """Facility Model Definition"""

    class Meta:
        verbose_name_plural = "Facilities"


class HouseRule(AbstractItem):
    """HouseRule Model Definition"""

    class Meta:
        verbose_name = "House Rule"


class Room(core_models.TimeStampedModel):
    """Room Model Definition"""

    name = models.CharField(max_length=140)
    description = models.TextField()
    country = CountryField()
    city = models.CharField(max_length=80)
    price = models.IntegerField()
    address = models.CharField(max_length=140)
    guests = models.IntegerField()
    beds = models.IntegerField()
    bedrooms = models.IntegerField()
    baths = models.IntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField(default=False)
    host = models.ForeignKey(
        "users.User", related_name="rooms", on_delete=models.CASCADE
    )
    room_type = models.ForeignKey(
        "RoomType", related_name="rooms", on_delete=models.SET_NULL, null=True
    )
    amenities = models.ManyToManyField("Amenity", related_name="rooms", blank=True)
    facilities = models.ManyToManyField("Facility", related_name="rooms", blank=True)
    house_rules = models.ManyToManyField("HouseRule", related_name="rooms", blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.city = str.capitalize(self.city)
        super().save(*args, **kwargs)

    def total_rating(self):
        all_reviews = self.reviews.all()
        all_ratings = 0
        if (len(all_reviews)) > 0:
            for review in all_reviews:
                all_ratings += review.rating_average()
            return round(all_ratings / len(all_reviews), 2)
        return 0

    def first_photo(self):
        try:
            (photo,) = self.photos.all()[:1]
            return photo.file.url
        except ValueError:
            return None

    def get_absolute_url(self):
        return reverse("rooms:detail", kwargs={"pk": self.pk})

    def get_next_four(self):
        photos = self.photos.all()[1:5]
        return photos

    def get_calendars(self):
        today = datetime.date.today()
        nextmonth = today + relativedelta.relativedelta(months=1)
        this_month = Calendar(today.year, today.month)
        next_month = Calendar(nextmonth.year, nextmonth.month)
        return [this_month, next_month]


class Photo(core_models.TimeStampedModel):
    """Photo Model Definition"""

    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to="room_photos")
    room = models.ForeignKey("Room", related_name="photos", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption

rooms/forms.py
from django import forms
from django_countries.fields import CountryField
from . import models


class SearchForm(forms.Form):
    """SearchForm Definition"""

    city = forms.CharField(initial="Anywhere")
    country = CountryField(default="KR").formfield()
    room_type = forms.ModelChoiceField(
        required=False, empty_label="Any kind", queryset=models.RoomType.objects.all()
    )
    price = forms.IntegerField(required=False)
    guests = forms.IntegerField(required=False)
    bedrooms = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)
    instant_book = forms.BooleanField(required=False)
    superhost = forms.BooleanField(required=False)
    amenities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Amenity.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    facilities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Facility.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )


class CreatePhotoForm(forms.ModelForm):
    class Meta:
        model = models.Photo
        fields = ("caption", "file")

    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)
        room = models.Room.objects.get(pk=pk)
        photo.room = room
        photo.save()


class CreateRoomForm(forms.ModelForm):
    class Meta:
        model = models.Room
        fields = (
            "name",
            "description",
            "country",
            "city",
            "price",
            "address",
            "guests",
            "beds",
            "bedrooms",
            "baths",
            "check_in",
            "check_out",
            "instant_book",
            "room_type",
            "amenities",
            "facilities",
            "house_rules",
        )

    def save(self, *args, **kwargs):
        room = super().save(commit=False)
        return room

rooms/views.py
from django.http import Http404
from django.views.generic import ListView, DetailView, View, UpdateView, FormView
from django.utils import timezone
from django.shortcuts import redirect, render
from django.urls import reverse
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from users import mixins as user_mixins
from . import models, forms


class HomeView(ListView):
    """Homeview Definition"""

    model = models.Room
    paginate_by = 12
    ordering = "created"
    paginate_orphans = 5
    context_object_name = "rooms"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        now = timezone.now()
        context["now"] = now
        return context


class RoomDetail(DetailView):
    """RoomDetail Definition"""

    model = models.Room
    context_object_name = "room"


class SearchView(View):
    def get(self, req):
        country = req.GET.get("country")

        if country:

            form = forms.SearchForm(req.GET)

            if form.is_valid():
                city = form.cleaned_data.get("city")
                country = form.cleaned_data.get("country")
                room_type = form.cleaned_data.get("room_type")
                price = form.cleaned_data.get("price")
                guests = form.cleaned_data.get("guests")
                bedrooms = form.cleaned_data.get("bedrooms")
                beds = form.cleaned_data.get("beds")
                baths = form.cleaned_data.get("baths")
                instant_book = form.cleaned_data.get("instant_book")
                superhost = form.cleaned_data.get("superhost")
                amenities = form.cleaned_data.get("amenities")
                facilities = form.cleaned_data.get("facilities")

                filter_args = {}

                if city != "Anywhere":
                    filter_args["city__startswith"] = city

                filter_args["country"] = country

                if room_type is not None:
                    filter_args["room_type"] = room_type

                if price is not None:
                    filter_args["price__lte"] = price

                if guests is not None:
                    filter_args["guests__gte"] = guests

                if bedrooms is not None:
                    filter_args["bedrooms__gte"] = bedrooms

                if beds is not None:
                    filter_args["beds__gte"] = beds

                if baths is not None:
                    filter_args["baths__gte"] = baths

                if instant_book is True:
                    filter_args["instant_book"] = True

                if superhost is True:
                    filter_args["host__superhost"] = True

                for amenity in amenities:
                    filter_args["amenities"] = amenity

                for facility in facilities:
                    filter_args["facilities"] = facility

                qs = models.Room.objects.filter(**filter_args).order_by("pk")

                paginator = Paginator(qs, 10, orphans=5)

                page = req.GET.get("page", 1)

                rooms = paginator.get_page(page)
                print(rooms, vars(rooms))
                return render(
                    req,
                    "rooms/search.html",
                    {"form": form, "rooms": rooms},
                )
        else:
            form = forms.SearchForm()

        return render(
            req,
            "rooms/search.html",
            {
                "form": form,
            },
        )


class EditRoomView(user_mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):

    model = models.Room
    template_name = "rooms/room_edit.html"
    fields = (
        "name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "guests",
        "beds",
        "bedrooms",
        "baths",
        "check_in",
        "check_out",
        "instant_book",
        "room_type",
        "amenities",
        "facilities",
        "house_rules",
    )

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            return Http404()
        return room


class RoomPhotosView(user_mixins.LoggedInOnlyView, DetailView):
    model = models.Room
    template_name = "rooms/room_photos.html"

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            return Http404()
        return room


@login_required()
def delete_photo(request, room_pk, photo_pk):
    user = request.user
    try:
        room = models.Room.objects.get(pk=room_pk)
        if room.host.pk != user.pk:
            messages.error(request, "Can not delete that photo")
        else:
            models.Photo.objects.filter(pk=photo_pk).delete()
            messages.success(request, "Photo deleted")
        return redirect(reverse("rooms:photos", kwargs={"pk": room_pk}))
    except models.Room.DoesNotExist:
        return redirect(reverse("core:home"))


class EditPhotoView(user_mixins.LoggedInOnlyView, UpdateView):

    model = models.Photo
    template_name = "rooms/photo_edit.html"
    fields = ("caption",)
    success_message = "Photo Updated"
    pk_url_kwarg = "photo_pk"

    def get_success_url(self):
        room_pk = self.kwargs.get("room_pk")
        return reverse("rooms:photos", kwargs={"pk": room_pk})


class AddPhotoView(user_mixins.LoggedInOnlyView, SuccessMessageMixin, FormView):

    template_name = "rooms/photo_add.html"
    form_class = forms.CreatePhotoForm

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        form.save(pk)
        messages.success(self.request, "Photo Uploaded")
        return redirect(reverse("rooms:photos", kwargs={"pk": pk}))


class CreateRoomView(user_mixins.LoggedInOnlyView, FormView):

    form_class = forms.CreateRoomForm
    template_name = "rooms/room_create.html"

    def form_valid(self, form):
        room = form.save()
        room.host = self.request.user
        room.save()
        room.save_m2m()
        messages.success(self.request, "Room created")
        return redirect(reverse("rooms:detail", kwargs={"pk": room.pk}))

templates/rooms/detail.html
{% extends "base.html" %}

{% block page_name %}Detail  {% endblock %}

{% block content %}
<div>
    <h1>{{room.name}}</h1>
    <h3>{{room.description}}</h3>
</div>
<div>
    <h2>By: {{room.host.username}}
        {% if room.host.superhost %}
            <h4>Superhost</h4>
        {% endif %}
    </h2>
    <h3>Amenities</h3>
    {% for a in room.amenities.all %}
        <li>{{a}}</li>
    {% endfor %}
    <h3>Facilities</h3>
    {% for f in room.facilities.all %}
        <li>{{f}}</li>
    {% endfor %}
    <h3>House Rules</h3>
    {% for r in room.house_rules.all %}
        <li>{{r}}</li>
    {% endfor %}
</div>
{% endblock %}

templates/rooms/photo_add.html
{% extends "base.html"%}
{% block page_title %}Upload Photo{% endblock %}

{% block search-bar %}{% endblock %}

{% block content %}
<div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
   
    {% include "mixins/room/room_form.html" with form=form cta="Upload Photo"%}

</div>
{% endblock %}

templates/rooms/photo_edit.html
{% extends "base.html"%}
{% block page_title %}Edit Photo{% endblock %}

{% block search-bar %}{% endblock %}

{% block content %}
<div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
   
    {% include "mixins/room/room_form.html" with form=form cta="Edit Photo"%}

</div>
{% endblock %}

templates/rooms/room_create.html
{% extends "base.html"%}
{% block page_title %}Create Room{% endblock %}

{% block search-bar %}{% endblock %}

{% block content %}
<div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
   
    {% include "mixins/room/room_form.html" with form=form cta="Room Create"%}

</div>
{% endblock %}

templates/rooms/room_detail.html
{% extends "base.html" %}
{% load is_booked %}
{% load on_favs i18n %}

{% block page_title %}{{room.name}}{% endblock %}

{% block content %}
    <div class="-mt-5 container max-w-full h-75vh mb-20 flex">
        <div class="h-full w-1/2 bg-cover" style="background-image:url({{room.first_photo}})"></div>
        <div class="h-full w-1/2 flex flex-wrap">
            {% for photo in room.get_next_four %}
                <div class="w-1/2 h-auto bg-cover bg-center border-gray-700 border" style="background-image:url({{photo.file.url}})"></div>
            {% endfor %}
        </div>
    </div>

    <div class="container mx-auto flex justify-around pb-56">
        <div class="w-1/2">
            <div class="flex justify-between">
                <div class="mb-5">
                    <h4 class="text-3xl font-medium mb-px">{{room.name}}</h4>
                    <span class="text-sm opacity-60 font-light">{{room.city}}</span>
                </div>
                <a href="{{room.host.get_absolute_url}}" class="flex flex-col items-center">
                    {% include "mixins/user_avatar.html" with user=room.host %}
                    <span class="mt-2 text-gray-500">{{room.host.first_name}}</span>
                </a>
            </div>
            {% on_favs room as fav_bool %}
            {% if fav_bool %}
            <a class="block mb-10 w-1/3 bg-red-400 p-2 text-center rounded-lg text-white" href="{% url 'lists:favRoom' room.pk %}?action=remove">Remove from Favorit</a>
            {% else %}
                <a class="block mb-10 w-1/3 bg-blue-300 p-2 text-center rounded-lg text-white" href="{% url 'lists:favRoom' room.pk %}?action=add">Save to Favorit</a>
            {% endif %}
            <div class="flex border-section">
                <span class="font-light mr-5">{{room.room_type}}</span>
                <span class="font-light mr-5">{{room.beds}} Bed{{room.beds|pluralize}}</span>
                <span class="font-light mr-5">{{room.bedrooms}} Bedroom{{room.bedrooms|pluralize}}</span>
                <span class="font-light mr-5">{{room.baths}} Bath{{room.baths|pluralize}}</span>
                <span class="font-light mr-5">{{room.guests}} Guest{{room.guests|pluralize}}</span>
            </div>
            <p class="border-section">
                {{room.description}}
            </p>
            <div class="border-section">
                <h4 class="font-medium text-lg mb-5">Amenities</h4>
                {% for a in room.amenities.all %}
                    <li class="mb-2">{{a}}</li>
                {% endfor %}
            </div>
            <div class="border-section">
                <h4 class="font-medium text-lg mb-5">Facilities</h4>
                {% for a in room.facilities.all %}
                    <li class="mb-2">{{a}}</li>
                {% endfor %}
            </div>
            <div class="border-section">
                <h4 class="font-medium text-lg mb-5">House Rules</h4>
                {% for a in room.house_rules.all %}
                    <li class="mb-2">{{a}}</li>
                {% endfor %}
            </div>
            <div class="mt-6">
                <h4 class="font-medium text-2xl mb-5">Reviews</h4>
                <div class="flex items-center">
                    <div>
                        <i class="fas fa-star text-green-400"></i>
                        <span class="font-bold text-xl">{{room.total_rating}}</span>
                    </div>
                    <div class="h-5 w-px bg-gray-400 mx-5"></div>
                    <div>
                        <span class="font-bold text-xl">{{room.reviews.count}}</span>
                        <span>Review{{rom.reviews|pluralize}}</span>
                    </div>
                </div>
                <div class="mt-10">
                    {% for re in room.reviews.all %}
                    <div class="border-section">
                        <div class="mb-5 flex">
                            <div>
                                {% include "mixins/user_avatar.html" with user=re.user text='xl' h_and_w="w-10 h-10"%}
                            </div>
                            <div class="flex flex-col ml-3">
                                <span class="font-medium">{{re.user.first_name}}</span>
                                <span class="text-sm  text-gray-500">{{re.created|date:'F Y'}}</span>
                            </div>
                        </div>
                        <p>{{re.review}}</p>
                    </div>
                    {% endfor %}
                </div>
            </div>          
        </div>
    <div class="w-1/3">
        {% if room.host == user %}
            <a href="{% url "rooms:edit" room.pk %}" class="btn-link block">Edit Room</a>
        {% else %}
            {% if not request.session.is_hosting %}
                {% for cal in room.get_calendars %}
                    <div class="mb-20">
                        <span class="mb-8 text-center font-medium text-lg block">{{cal.get_month}} / {{cal.year}}</span>
                        <div class="grid grid-cols-7 gap-2.5 justify-items-center mb-4 font-semibold" >
                            {% for day in cal.day_names %}
                                <span>{{day}}</span>
                            {% endfor %}
                            {% for day in cal.get_days %}
                                {% is_booked room day as is_booked_bool %}
                                {% if day.number != 0 %}
                                    {% if day.past %}
                                        <span class="rounded bg-gray-200 w-full text-center p-1 text-gray-400">{{day.number}}</span>
                                    {% elif is_booked_bool %}
                                        <span class="rounded bg-gray-200 w-full text-center p-1 text-gray-400 line-through">{{day.number}}</span>
                                    {% else %}
                                        <a href="{% url 'reservations:create' room.pk day.year day.month day.number %}" class="hover:bg-blue-300 hover:text-white bg-gray-200 text-center w-full rounded p-1 text-gray-600 cursor-pointer">{{day}}</a>
                                    {% endif %}
                                {% else %}
                                    <span></span>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        {% endif %}
    </div>
    </div>
{% endblock %}

templates/rooms/room_edit.html
{% extends "base.html"%}
{% block page_title %}Update Room{% endblock %}

{% block search-bar %}{% endblock %}

{% block content %}
<div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
   
    {% include "mixins/room/room_form.html" with form=form cta="Update Room"%}
    

    <div class="mt-5">
        <a href="{% url 'rooms:photos' room.pk %}" class="text-blue-300">Edit Photos</a>
    </div>


</div>
{% endblock %}

templates/rooms/room_list.html
{% extends "base.html" %}

{% block page_title %}Home{% endblock %}

{% block content %}
    <div class="container mx-auto pb-10">
        <div class="rounded-2xl bg-gray-800  -mx-20  h-50vh mt-32 mb-24 bg-cover bg-center" style="background-image:url(https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2064&q=80)"></div>

        <div class="flex flex-wrap -mx-20 mb-10">
            {% for room in  rooms %}
                {% include 'mixins/room_card.html' with room=room %}
            {% endfor %}
        </div>

        <div class="flex item-center mx-auto container justify-center">
            {% if page_obj.has_previous %}
                <a href="?page={{page_obj.previous_page_number}}" class="text-blue-400 flex items-center">
                    <i class="fas fa-arrow-left fa-lg"></i>
                </a>
            {% endif %}
                <span class="mx-3 font-medium text-lg">{{page_obj.number}} of {{page_obj.paginator.num_pages}}</span>
            {% if page_obj.has_next %}
                <a href="?page={{page_obj.next_page_number}}" class="text-blue-400 flex item-center" >
                    <i class="fas fa-arrow-right fa-lg"></i>
                </a>
            {% endif %}
        </div>
    </div>
{% endblock %}
    

templates/rooms/room_photos.html
{% extends "base.html"%}
{% block page_title %}
{{room.name}}'s Photos
{% endblock %}

{% block search-bar %}{% endblock %}

{% block content %}
<div class="container mx-auto my-10 flex flex-col">

    <div class="my-10 w-full">
        <a href="{% url 'rooms:add-photo' room.pk %}" class="btn-link w-1/3 block">Upload Photo</a>
    </div>
   
    {% for photo in room.photos.all %}
        <div class="mb-5 border p-6 border-gray-400 flex justify-between">
            <div class="flex items-start">
                <img src="{{photo.file.url}}" class="w-32 h-32"/>
                <span class="ml-5 text-xl">{{photo.caption}}</span>
            </div>
            <div class="flex flex-col w-1/5">
                <a class="btn-link mb-5" href="{% url "rooms:edit-photo" room.pk photo.pk %}">Edit</a>
                <a class="btn-link bg-red-600" href="{% url 'rooms:delete-photo' room.pk photo.pk %}">Delete</a>
            </div>
        </div>
    {% endfor %}

    <div class="flex justify-center">
        <a href="{% url 'rooms:edit' room.pk %}" class="text-blue-300 font-medium font-2xl"><i class="fas fa-chevron-left mr-1"></i> Back To Edit Room</a>
    </div>

</div>
{% endblock %}

templates/rooms/search.html
{% extends "base.html"%}
{% block page_title %}Search{% endblock %}

{% block search-bar %}{% endblock %}
{% block content %}
<h2>Search Bar</h2>
<form method="get" action='{% url "rooms:search" %}'>
    {{form.as_p}}
    <button>Search</button>
</form>
<h2>Results</h2>
{% for x in rooms %}
<h3>{{x.name}}</h3>
{% endfor %}

{% if rooms.paginator.has_previous %}
    <a href="?page={{rooms.paginator.previous_page_number}}">Previous</a>
{% endif %}

<h1> Page {{rooms.number}}  of {{rooms.paginator.num_pages}}</h1>

{% if rooms.paginator.has_next %}
    <a href="?page={{rooms.paginator.next_page_number}}">Next</a>
{% endif %}

{% endblock %}